apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: testapp2
spec:
  selector:
    matchLabels:
      app: testapp2
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      containers:
      - name: testapp2
        image: testapp2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000