apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: web-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          # resources:
          #  requests:
          #   cpu: 1
          #   memory: "100M"
          #  limits:
          #   cpu: 1
          #   memory: "100M"

---
kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: app-service
              servicePort: 8080

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: app-deployment
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: app-deployment
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50