apiVersion: batch/v1
kind: Job
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        image: application:latest
        imagePullPolicy: Never
      restartPolicy: OnFailure