apiVersion: apps/v1
kind: pod
spec:
  selector:
    matchLabels:
      app: crawler
  serviceName: "crawler"
  replicas: 1
  template:
    metadata:
      labels:
        app: crawler
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: crawler
          image: mo
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          ports:
            - containerPort: 3306
            - containerPort: 33060
          volumeMounts:
          - name: mongo-volume
            mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi