apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  clusterIP: None
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017