apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb-standalone
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo:4.0.8
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
      nodeSelector:
        kubernetes.io/hostname: mongodb-node
      volumeMounts:
            - name: data-volume
              mountPath: /docker-entrypoint-initdb.d/
      ports:
        - containerPort: 3306
        - containerPort: 33060
      livenessProbe:
        tcpSocket:
          port: 33060
        initialDelaySeconds: 300 
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 33060
        initialDelaySeconds: 5
        periodSeconds: 10
      volumes:
        - name: data-volume
          emptyDir: {}
