apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - name: mongo-prot
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: mongo-xproto
      protocol: TCP
      port: 33060
      targetPort: 33060
