apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deployment
    labels:
        app: app-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: web-app
    template:
        metadata:
            labels:
                app: web-app
        spec:
            containers:
                - name: web-app
                  image: # chech which image!
                  imagePullPolicy: Never
                  ports:
                    - containerPort: 8080
                ressources:
                    requests:
                        cpu: 1
                        memory: 200M
                    limits:
                        cpu: 2
                        memory: 400M

---

apiVersion: v1
kind: Service
metadata:
    name: app-service
spec:
    selector:
        app: web-app
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: app-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - http:
            paths:
                - path: /
                  backend:
                    serviceName: app-service
                    servicePort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: memcache-deployment
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: app-deployment
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50