apiVersion: apps/v1
kind: Deployment
metadata:
    name: memcache-deployment
    labels:
        app: memcache-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: memcache
        template:
            metadata:
                labels:
                    app: memcache
            spec:
                containers:
                    - name: memcache
                      image: memcached:alpine
                      ports:
                        - containerPort: 11211
                    ressources:
                        requests:
                            cpu: 1
                            memory: 200M
                        limits:
                            cpu: 2
                            memory: 400M

---

apiVersion: v1
kind: Service
metadata:
    name: memcache-service
spec:
    clusterIP: None
    selector:
        app: memcache

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: memcache-deployment
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: memcache-deployment
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50